
  services:
    redis:
      image: redis:8.0
      ports:
       - 6379:6379
      volumes:
        - db-data:/data
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 5s

    flask:
      build: .
      ports:
        - 5001:5000
      networks:
        - app-network
      environment:
        REDIS_OM_URL: redis://redis:6379
      depends_on:
        - redis
    

  volumes:
      db-data:

  networks:
      app-network:
      
